import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/lib/queryClient";
import { initAuth } from "@/lib/auth";
import { useEffect, useState } from "react";
import { Toaster } from "sonner";
import { ErrorBoundary } from "@/lib/ErrorBoundary";
import "./styles.css";

// Import route tree generated by TanStack Router
import { routeTree } from "./routeTree.gen";

// Register router types
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

// Create router
const router = createRouter({ routeTree });

// Root component with auth provider
function App() {
  const [isInitialized, setIsInitialized] = useState(false);

  useEffect(() => {
    initAuth();
    setIsInitialized(true);
  }, []);

  if (!isInitialized) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-900">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" role="status" aria-label="Loading">
          <span className="sr-only">Loading...</span>
        </div>
      </div>
    );
  }

  return (
    <ErrorBoundary>
      <QueryClientProvider client={queryClient}>
        <RouterProvider router={router} />
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            classNames: {
              toast: "bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 shadow-lg",
              title: "text-gray-900 dark:text-white",
              description: "text-gray-600 dark:text-gray-400",
              success: "border-green-500",
              error: "border-red-500",
              warning: "border-yellow-500",
              info: "border-blue-500",
            },
          }}
        />
      </QueryClientProvider>
    </ErrorBoundary>
  );
}

// Render app
const container = document.getElementById("root");
if (container) {
  const root = createRoot(container);
  root.render(<App />);
}
